apis:
  # SMTP 服务器配置
  smtp:
    # 发送邮箱
    sender_email: '***@qq.com'
    # smtp服务器信息
    smtp_server: 'smtp.qq.com'
    smtp_port: 587 
    # 邮箱认证信息
    username: '***@qq.com'
    password: '***'

users:
  - user:
      # full_train_code 车次号 必填 大小写区分
      full_train_code: K257
      # trainDate 发车日期 格式 2021-03-01
      trainDate: '2023-10-11'
      # from_station_name 始发站
      from_station_name: 安阳
      #to_station_name 终点站 
      to_station_name: 郑州
      #seat_type_name 无座 硬座 硬卧 软卧  
      seat_type_name: 硬座
      #email 接受通知消息的邮箱
      email: *****@qq.com
      #seat_yupiao 大于余票数发消息 默认值为0
      seat_yupiao: 0